CREATE TABLE `user` (
   `userid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   `firstname` VARCHAR(255) NOT NULL,
   `lastname` VARCHAR(255) NOT NULL,
   `email` VARCHAR(255) NOT NULL,
   `hashedpassword` VARCHAR(520) NOT NULL,
   `passwordrecoverytoken` VARCHAR(255) NULL,
   `passwordrecoveryexpire` BIGINT UNSIGNED NULL,
   PRIMARY KEY (`userid`));

ALTER TABLE `user`
    ADD UNIQUE INDEX `passwordrecoverytoken_UNIQUE` (`passwordrecoverytoken` ASC) VISIBLE;

CREATE TABLE `mobilityreview` (
 `idmobilityreviewid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 `reviwed` TINYINT(1) UNSIGNED NOT NULL,
 `firstname` VARCHAR(255) NULL,
 `lastname` VARCHAR(255) NULL,
 `sector` TEXT NOT NULL,
 `mobilityyear` TEXT NOT NULL,
 `allowcontact` TINYINT(1) UNSIGNED NOT NULL,
 `email` VARCHAR(255) NULL,
 `linkedin` VARCHAR(255) NULL,
 `countrycode` VARCHAR(45) NOT NULL,
 `city` VARCHAR(255) NOT NULL,
 `hostorganization` TEXT NOT NULL,
 `ismobilityprofessional` TINYINT(1) UNSIGNED NOT NULL,
 `contractstatuswhilemobility` INT UNSIGNED NOT NULL,
 `contractstatusdetailswhilemobility` TEXT NULL,
 `mobilityperiod` TEXT NOT NULL,
 `hadbreaks` TINYINT(1) UNSIGNED NOT NULL,
 `breaksdetails` TEXT NOT NULL,
 `neededvisa` TINYINT(1) UNSIGNED NOT NULL,
 `visadetails` TEXT NULL,
 `visadelaysforasking` TEXT NULL,
 `visatips` TEXT NULL,
 `visacost` TEXT NULL,
 `vaccinationdetails` TEXT NULL,
 `transportationmeans` TEXT NOT NULL,
 `transportationdetails` TEXT NULL,
 `accommodationtype` TEXT NOT NULL,
 `accommodationdetails` TEXT NULL,
 `accomodationcost` TEXT NOT NULL,
 `livingcost` TEXT NOT NULL,
 `financialaid` TEXT NOT NULL,
 `neededtoopenbankaccount` TINYINT(1) UNSIGNED NOT NULL,
 `spokenlanguage` TEXT NOT NULL,
 `languagelevel` TEXT NOT NULL,
 `integration` TEXT NOT NULL,
 `prosandconsofthecountry` TEXT NOT NULL,
 `tipsforthecountry` TEXT NOT NULL,
 `whatwouldyouchange` TEXT NOT NULL,
 `adviceforfuturemobilitystudents` TEXT NOT NULL,
 PRIMARY KEY (`idmobilityreviewid`));
